[package]
name = "os"
version = "0.1.0"
authors = ["Moocow9m <649310-Moocow9m@users.noreply.gitlab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
